Repository match-gg/MATCH_FE, pull requests merged in 2023-05, with the labels that each got.

#75 refactor : 롤 body
  src/components/main/lol/BoardFilter.js
  src/components/main/lol/Body.d.js
  src/components/main/lol/Body.js
  src/components/main/lol/LolBody.js
  src/pages/LeagueofLegends.js
Labels: 🔨 Refactor

#79 Feat : 파티 만료시간에 타이머 적용
  package-lock.json
  package.json
  src/components/main/lol/Card.js
  src/components/main/lol/CardDetailModal.js
  src/components/main/lol/boards.tmp.js
Labels: ✨ Feature

#92 채팅방과 백엔드 서버 연동 기능 추가
  .DS_Store
  .gitignore
  src/.DS_Store
  src/chat/ChatList.js
  src/chat/ChatRoom.js
  src/chat/TestButton.js
  src/components/.DS_Store
  src/components/main/.DS_Store
  src/components/main/lol/BoardFilter.js
  src/components/main/lol/Body.js
  src/components/main/lol/Card.js
  src/components/main/lol/CreateCardBtn.js
  src/store/chatRoom-slice.js
Labels: ✨ Feature, 📬 API

#100 Feat : 카드 상세보기 모달에서 파티 가입 시 채팅 기능 구현, 기존 채팅 구조 수정 반영
  src/chat/ChatCard.js
  src/chat/ChatInCardDetailModal.js
  src/chat/ChatList.js
  src/chat/ChatMessage.js
  src/chat/ChatMessageInDetail.js
  src/chat/ChatRoom.js
  src/chat/ChatToggleBtn.js
  src/chat/CreateChatroomBtn.js
  src/components/main/lol/BoardFilter.js
  src/components/main/lol/CardDeatilModal.js
  src/components/main/lol/JoinPartyButton.js
  src/components/main/lol/LeavePatryButton.js
  src/store/chatRoom-slice.js
Labels: ✨ Feature

#103 Feat : 파이어베이스 Realtime DB 구조 변경에 의한 CreateCardBtn의 게시글 생성 함수 코드 수정
  src/chat/ChatInCardDetailModal.js
  src/chat/ChatRoom.js
  src/components/main/lol/CreateCardBtn.js
  src/components/main/lol/LeavePatryButton.js
Labels: ✨ Feature

#109 Feat : 파티원 상세조회 기능 구현
  src/components/main/lol/PartyMember.js
Labels: ✨ Feature

#105 Feat : 비로그인 사용자 기능 제한
  src/components/main/MainHeader.js
  src/components/main/lol/BoardFilter.js
Labels: ✨ Feature

#113 Fix : 채팅까지의 오류 잡기
  src/chat/ChatInCardDetailModal.js
  src/chat/ChatMessageInDetail.js
  src/components/MyPage/MyInfo.js
  src/components/Register/GameIcon.js
  src/components/Register/InputGameInfo.js
  src/components/Register/RegisterFooter.js
  src/components/main/MainHeader.js
  src/components/main/lol/Body.js
  src/components/main/lol/CardDeatilModal.js
  src/components/main/lol/CreateCardBtn.js
  src/components/main/lol/JoinPartyButton.js
  src/components/main/lol/LeavePatryButton.js
  src/components/main/lol/LolPageNavbar.js
  src/components/main/lol/prevCardDetailModal.js
  src/components/main/valorant/ValorantBody.js
  src/pages/KakaoLoginRedirect.js
  src/pages/MyPage.js
Labels: 🐞 BugFix, ✨ Feature, :art: Design

#114 Feat : 강퇴 기능 구현, 강퇴 기능 구현에 따른 Firebase RealtimeDB 구조 관련 코드 수정
  src/chat/ChatInCardDetailModal.js
  src/chat/TestButton.js
  src/components/main/MainHeader.js
  src/components/main/lol/BoardFilter.js
  src/components/main/lol/Body.d.js
  src/components/main/lol/Body.js
  src/components/main/lol/CardDeatilModal.js
  src/components/main/lol/JoinPartyButton.js
  src/components/main/lol/PartyMember.js
  src/store/index.js
Labels: 🐞 BugFix, ✨ Feature

#128 Feat : 채팅방 생성시 Firebase Realtime DB에 게임 종류 저장
  src/components/main/lol/CreateCardBtn.js
Labels: ✨ Feature

#130 Fix : 백엔드 서버 배포 전 테스트간 발생한 버그 수정
  package-lock.json
  package.json
  src/chat/ChatInCardDetailModal.js
  src/chat/ChatMessageInDetail.js
  src/components/main/lol/Body.js
  src/components/main/lol/Card.d.js
  src/components/main/lol/Card.js
  src/components/main/lol/CardDeatilModal.js
  src/components/main/lol/CardRecruitmentStatus.js
  src/components/main/lol/CreateCardBtn.js
  src/components/main/lol/DeletePartyButton.js
  src/components/main/lol/JoinPartyButton.js
  src/components/main/lol/LeavePatryButton.js
  src/components/main/lol/PartyMember.js
  src/pages/KakaoLoginRedirect.js
  src/setupProxy.js
Labels: 🐞 BugFix

#131 Feat : 게시글 작성자가 직접 파티원을 추가하는 기능 구현
  src/components/main/lol/CardDeatilModal.js
  src/components/main/lol/Recruitment.js
Labels: ✨ Feature

#133 Fix : 게시글 작성자가 직접 파티 멤버에 추가한 멤버도 강퇴할 수 있도록 수정
  src/components/main/lol/CardDeatilModal.js
  src/components/main/lol/PartyMember.js
  src/components/main/lol/Recruitment.js
Labels: 🐞 BugFix
