Repository match-gg/MATCH_FE, pull requests merged in 2023-03, with the labels that each got.

#33 feat : 회원가입 - 게임별 정보 입력
  src/components/Register/RegisterFooter.js
  src/components/Register/RegisterWrapper.js
Labels: ✨ Feature, 📬 API

#32 feat: 마이페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/components/MyPage/FollowItem.js
  src/components/MyPage/FollowList.js
  src/components/MyPage/MyInfo.js
  src/components/MyPage/MyPageHeader.js
  src/components/MyPage/MyPageLayout.js
  src/components/MyPage/PersonalInfo.js
  src/components/MyPage/Sidebar.js
  src/components/MyPage/Withdraw.js
  src/pages/MyPage.js
Labels: ✨ Feature

#42 로그인/회원가입 나누기
  package-lock.json
  package.json
  src/App.js
  src/components/Register/GameIcon.js
  src/components/Register/InputGameInfo.js
  src/components/Register/RegisterBody.js
  src/components/Register/RegisterFavGame.js
  src/components/Register/RegisterFooter.js
  src/components/Register/RegisterGames.js
  src/components/Register/RegisterHeader.js
  src/components/Register/RegisterSuccess.js
  src/components/Register/RegisterTerms.js
  src/components/Register/RegisterWrapper.js
  src/components/Register/TermSection.js
  src/components/Register/datas/Game.data.js
  src/components/Register/datas/Register.data.js
  src/components/main/lol/LolPageNavbar.js
  src/components/ui/Divider.js
  src/components/ui/KakaoLoginBtn.js
  src/pages/KakaoLoginRedirect.js
  src/pages/LoginPage.js
  src/pages/RegisterPage.js
  src/store/index.js
  src/store/register-slice.js
Labels: ✨ Feature, 🔨 Refactor

#47 게시글 불러오기 및 필터링
  src/components/main/lol/Card.js
  src/components/main/lol/LolPage.js
Labels: ✨ Feature
